### ISSUE TITLE
Is there a way to toggle between command modes and normal text to speach?

### ISSUE THREAD

**Issue by sanbornm** [pselle/macvimspeak#1]
Use case using vimperator in chrome.

**Comment by pselle** [comment]
The "ssh" command tells MacVimSpeak to stop listening for Vim commands, I don't recall what happens when you hit "fn fn" during that time (to turn on native dictation https://support.apple.com/en-us/HT202584).

I'm making the assumption you mean dictation when you say text to speech, but if you actually mean text to speech (your computer talking to you, not you talking to your computer) there's probably a way to prevent MacVimSpeak from muting system audio.

**Comment by sanbornm** [comment]
Sorry for the confusion, I meant voice to text.  You are right if you tell MacVimSpeak to shush and and use the preconfigured keys to activate normal voice to text it does work however on my machine when I do this it becomes fairly unresponsive I think possibly two listeners are running?

When I click stop listening and activate normal voice to text it works fine.  I was looking for maybe another command like "sush/wakeup" to temporarily bypass MacVimSpeak and activate normal voice to text.

I would attempt to add this myself but I have no idea where to begin with swift.  Thanks for taking the time and writing this tool. :smile:

**Comment by pselle** [comment]
The shush command's idea is to leave voice recognition running, so that it doesn't have to spend the time reloading commands ... there could be a command to turn MacVimSpeak off, and then maybe even activate native dictation, but I haven't thought of a way for the system to turn on by voice once it's been turned off!

And yup, the two listeners running is pretty heavy on the computer in my experience!

I'll consider adding another command ("shut off"?) to turn off the system completely, or maybe (preferably) make that command optional.

And thank you! Thanks for using it!
